// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int N = Integer.parseInt(args[0]);
		int above = 0;
		int under = 0;
		double Ratio = 55 / 45;
		boolean t = true;

		for (int i = 0; i < N; i++){
			double x = Math.random();
			if (x > 0.5){
				above ++;
				}
			else{
				under ++;
			 }
			}

			//System.out.println(t + ", " + above + ", " + under + ", " + Ratio);

		if (above == 0 || under == 0){
			
			t = false;
		}
		else {
			Ratio = (0.5 * above) /  (0.5 * under) ;
		}

			System.out.println("> 0.5: " + above + " times" );
			System.out.println("<= 0.5: " + under + " times" );
			if(t==true){
				System.out.println("Ratio: " + Ratio);
			}

		}

	}

